name = "spinogambino-jeux-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-jeux.fr"
HMAC_KEY = "d24fbad034f682326f238343c7ba4dc3f00a38683543eee133eea1f14905c233"
COOKIE_NAME = "2l7"
PLAY_PATH = "visit"
BUTTON_ID = "p363cd4b06aa1bd02308a83ce5ca1cf79"
GATE_SALT = "f7f9778228e9b790"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "1cuv"
CTA_SELECTOR = ".play-button"
