name = "spinogambino-jeux-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-jeux.fr"
HMAC_KEY = "d24fbad034f682326f238343c7ba4dc3f00a38683543eee133eea1f14905c233"
COOKIE_NAME = "wpi"
PLAY_PATH = "launch"
BUTTON_ID = "p363cd4b06aa1bd02308a83ce5ca1cf79"
GATE_SALT = "8ee0153ffacbd0d3"
